name = "Adritian Free Hugo Theme"
license = "MIT"
licenselink = "https://github.com/zetxek/adritian-free-hugo-theme/blob/master/LICENSE"
description = "A free Hugo Theme by Radity: Modern, Fast, Fresh and of course responsive."
homepage = "https://www.adrianmoreno.info/"
tags = ['personal-website', 'personal', 'portfolio', 'single-page', 'one-page', 'fast', 'typography', 'customizable', 'mobile', 'resume', 'fresh', 'modern', 'flexbox', 'hugo-theme', 'hugo', 'bootstrap', 'responsive', 'clean', 'simple', 'creative', 'contact form', 'light', 'white', 'custom-design', 'minimal', 'minimalistic', 'minimalist', 'portfolio', 'google tag manager', 'google analytics', 'customizable', 'flexbox', 'starter', 'theme']
features = ['responsive', 'bootstrap']
min_version = "0.59.0"

[author]
  name = "Adrián Moreno Peña"
  homepage = "https://www.adrianmoreno.info/"
